on:
  release:
    types: [published]

jobs:
  upload_library:
    name: Upload Javascript Library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} webusb-pos-printer.js
